#!/bin/bash
# SAM Start Script
# Generated by deploy_to_sam.py

SAM_PATH="/Users/vengatagirivenkatesan/sam/v1"

echo "🚀 Starting Solace Agent Mesh (SAM)..."
echo "SAM Path: $SAM_PATH"
echo ""
echo "📋 Available Agents:"
echo "  - exchange_rate_lookup_agent"
echo "  - find_my_ip_agent"
echo "  - country_information_agent"
echo "  - news_snapshot_agent"
echo "  - weather_trend_agent"
echo ""
echo "💡 After SAM starts, you can:"
echo "  1. Access the web interface (usually http://localhost:8000)"
echo "  2. Choose which agent to interact with"
echo "  3. Ask questions to any of the deployed agents"
echo ""

# Change to SAM directory
cd "$SAM_PATH"

# Create virtual environment if it doesn't exist
echo "🔧 Setting up virtual environment..."
if [ ! -d ".venv" ]; then
    echo "📦 Creating new virtual environment..."
    python3 -m venv .venv
else
    echo "✅ Virtual environment already exists"
fi

# Activate virtual environment
echo "🔌 Activating virtual environment..."
source .venv/bin/activate

# Start SAM
echo "🔄 Starting SAM..."
sam run
