#!/bin/bash
# SAM Run Script for country_information_agent
# Generated by deploy_to_sam.py

SAM_PATH="/Users/vengatagirivenkatesan/sam/v1"
AGENT_CONFIG="$SAM_PATH/configs/agents/country_information_agent.yaml"

echo "🚀 Starting country_information_agent with SAM..."
echo "SAM Path: $SAM_PATH"
echo "Agent Name: country_information_agent"
echo "Config: $AGENT_CONFIG"

# Change to SAM directory
cd "$SAM_PATH"

# Run the agent
sam run "$AGENT_CONFIG"
